config/routes.rb
Rails.application.routes.draw do
  resources :premiations
  resources :badges
  resources :donations
  resources :materials
  resources :citizens
  resources :ecopoints
  devise_for :users
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ecopoint.rb
class Ecopoint < ApplicationRecord
  belongs_to :user
end

app/controllers/ecopoints_controller.rb
class EcopointsController < ApplicationController
  before_action :set_ecopoint, only: [:show, :edit, :update, :destroy]

  # GET /ecopoints
  # GET /ecopoints.json
  def index
    @ecopoints = Ecopoint.all
  end

  # GET /ecopoints/1
  # GET /ecopoints/1.json
  def show
  end

  # GET /ecopoints/new
  def new
    @ecopoint = Ecopoint.new
  end

  # GET /ecopoints/1/edit
  def edit
  end

  # POST /ecopoints
  # POST /ecopoints.json
  def create
    @ecopoint = Ecopoint.new(ecopoint_params)

    respond_to do |format|
      if @ecopoint.save
        format.html { redirect_to @ecopoint, notice: 'Ecopoint was successfully created.' }
        format.json { render :show, status: :created, location: @ecopoint }
      else
        format.html { render :new }
        format.json { render json: @ecopoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ecopoints/1
  # PATCH/PUT /ecopoints/1.json
  def update
    respond_to do |format|
      if @ecopoint.update(ecopoint_params)
        format.html { redirect_to @ecopoint, notice: 'Ecopoint was successfully updated.' }
        format.json { render :show, status: :ok, location: @ecopoint }
      else
        format.html { render :edit }
        format.json { render json: @ecopoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ecopoints/1
  # DELETE /ecopoints/1.json
  def destroy
    @ecopoint.destroy
    respond_to do |format|
      format.html { redirect_to ecopoints_url, notice: 'Ecopoint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ecopoint
      @ecopoint = Ecopoint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ecopoint_params
      params.require(:ecopoint).permit(:user_id)
    end
end

app/helpers/ecopoints_helper.rb
module EcopointsHelper
end

app/views/ecopoints/_form.html.erb
<%= form_with(model: ecopoint, local: true) do |form| %>
  <% if ecopoint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ecopoint.errors.count, "error") %> prohibited this ecopoint from being saved:</h2>

      <ul>
      <% ecopoint.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ecopoints/edit.html.erb
<h1>Editing Ecopoint</h1>

<%= render 'form', ecopoint: @ecopoint %>

<%= link_to 'Show', @ecopoint %> |
<%= link_to 'Back', ecopoints_path %>

app/views/ecopoints/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ecopoints</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ecopoints.each do |ecopoint| %>
      <tr>
        <td><%= ecopoint.user %></td>
        <td><%= link_to 'Show', ecopoint %></td>
        <td><%= link_to 'Edit', edit_ecopoint_path(ecopoint) %></td>
        <td><%= link_to 'Destroy', ecopoint, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ecopoint', new_ecopoint_path %>

app/views/ecopoints/new.html.erb
<h1>New Ecopoint</h1>

<%= render 'form', ecopoint: @ecopoint %>

<%= link_to 'Back', ecopoints_path %>

app/views/ecopoints/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @ecopoint.user %>
</p>

<%= link_to 'Edit', edit_ecopoint_path(@ecopoint) %> |
<%= link_to 'Back', ecopoints_path %>